spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/billing_dev}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:postgres}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
